scheduler:
  name: scheduler
  enabled: true
  image:
    repository: "ghcr.io/datvodinh/traffic-analysis"
    tag: latest
    pullPolicy: Always
    dask_worker: "dask-worker"

  replicas: 1
  serviceType: "ClusterIP"
  servicePort: 8786

worker:
  name: worker
  image:
    repository: "ghcr.io/datvodinh/traffic-analysis"
    tag: latest
    pullPolicy: Always
    dask_worker: "dask-worker"

  replicas: 4
  strategy:
    type: RollingUpdate
  default_resources:
    cpu: 3
    memory: "9GiB"
  portDashboard: 8790

jupyter:
  name: jupyter
  enabled: false
