scheduler:
  name: scheduler
  enabled: true
  image:
    repository: "ghcr.io/datvodinh/traffic-analysis"
    tag: latest
    pullPolicy: Always
  replicas: 1


worker:
  name: worker
  image:
    repository: "ghcr.io/datvodinh/traffic-analysis"
    tag: latest
    pullPolicy: Always

  replicas: 4
  strategy:
    type: RollingUpdate
  resources:
    limits:
      cpu: 3
      memory: 3G
    requests:
      cpu: 3
      memory: 3G

jupyter:
  name: jupyter
  enabled: false
