apiVersion: v1
data:
  DAGSTER_COMPUTE_LOG_PREFIX: dagster-log-
  DAGSTER_DEPLOYMENT: prod
  SPARK_URL: spark://spark-master-0.spark-headless.default.svc.cluster.local:7077
  CLICKHOUSE_URL: http://clickhouse.default.svc.cluster.local:9000

kind: ConfigMap
metadata:
  name: dagster-configmap
  namespace: default
