apiVersion: v1
data:
  DAGSTER_COMPUTE_LOG_PREFIX: dagster-log-
  DAGSTER_DEPLOYMENT: prod
  MINIO_URL: http://minio.default.svc.cluster.local:9000
  DASK_URL: tcp://dask-scheduler.default.svc.cluster.local:8786
  CLICKHOUSE_URL: http://clickhouse.default.svc.cluster.local:9000

kind: ConfigMap
metadata:
  name: dagster-configmap
  namespace: default
