apiVersion: v1
data:
  S3_BUCKET: traffic # This is the bucket name in Local Minio, no need secret.
  AWS_ENDPOINT_URL: http://minio.default.svc.cluster.local:9000
  DAGSTER_COMPUTE_LOG_PREFIX: dagster-log-
  DAGSTER_DEPLOYMENT: prod
  MINIO_URL: http://minio.default.svc.cluster.local:9000
  KAFKA_URL: kafka.default.svc.cluster.local:9092
  DASK_URL: tcp://dask-scheduler.default.svc.cluster.local:8786
  CLICKHOUSE_URL: http://clickhouse.default.svc.cluster.local:8123
  CLICKHOUSE_USER: default
  CLICKHOUSE_PASSWORD: "123456"
  AWS_ACCESS_KEY_ID: datvodinh
  AWS_SECRET_ACCESS_KEY: datvodinh
  TRAFFIC_DATA_PREFIX: ""

kind: ConfigMap
metadata:
  name: dagster-configmap
  namespace: default
