clusterDomain: cluster.local

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.9.0-debian-12-r1
  pullPolicy: IfNotPresent

listeners:
  client:
    containerPort: 9092
    protocol: SASL_PLAINTEXT
    name: CLIENT
    sslClientAuth: ""

  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
    sslClientAuth: ""

  interbroker:
    containerPort: 9094
    protocol: SASL_PLAINTEXT
    name: INTERNAL
    sslClientAuth: ""

  external:
    containerPort: 9095
    protocol: SASL_PLAINTEXT
    name: EXTERNAL
    sslClientAuth: ""

sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  oauthbearer:
    tokenEndpointUrl: ""
    jwksEndpointUrl: ""
    expectedAudience: ""
    subClaimName: "sub"
  interbroker:
    user: inter_broker_user
    password: ""
    clientId: inter_broker_client
    clientSecret: ""
  controller:
    user: controller_user
    password: ""
    clientId: controller_broker_client
    clientSecret: ""

  client:
    users:
      - user1
    passwords: ""

  zookeeper:
    user: ""
    password: ""

  existingSecret: ""

controller:
  replicaCount: 3
  controllerOnly: false
  minId: 0
  zookeeperMigrationMode: false
  resourcesPreset: "small"
  resources: {}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate

  pdb:
    create: true

  persistence:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    mountPath: /bitnami/kafka

broker:
  replicaCount: 0
  minId: 100
  resourcesPreset: "small"
  resources: {}
  automountServiceAccountToken: false
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce

    size: 8Gi
    mountPath: /bitnami/kafka

service:
  type: ClusterIP
  ports:
    client: 9092
    controller: 9093
    interbroker: 9094
    external: 9095
  externalTrafficPolicy: Cluster

externalAccess:
  enabled: false
  autoDiscovery:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: 1.31.2-debian-12-r6
      digest: ""

      pullPolicy: IfNotPresent

    resourcesPreset: "nano"
    resources: {}
  controller:
    forceExpose: false
    service:
      type: LoadBalancer
      ports:
        external: 9094
  broker:
    service:
      type: LoadBalancer
      ports:
        external: 9094

networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  addExternalClientAccess: true

serviceAccount:
  create: true
  name: "datvodinh"
  automountServiceAccountToken: false

kraft:
  enabled: true
