apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ExternalName
  externalName: host.docker.internal # For Docker Desktop on Windows/Mac
  ports:
    - port: 9000
      targetPort: 9000
