clusterDomain: cluster.local

image:
  registry: docker.io
  repository: bitnami/spark
  tag: 3.5.3-debian-12-r1
  digest: ""
  pullPolicy: IfNotPresent

hostNetwork: false

master:
  existingConfigmap: ""
  containerPorts:
    http: 8080
    https: 8480
    cluster: 7077
  automountServiceAccountToken: false
  resources:
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 1
      memory: 2G
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true

worker:
  existingConfigmap: ""
  containerPorts:
    http: 8080
    https: 8480
    cluster: ""
  automountServiceAccountToken: false
  replicaCount: 4
  resources:
    limits:
      cpu: 1
      memory: 4G
    requests:
      cpu: 1
      memory: 4G
  podAntiAffinityPreset: soft
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
  pdb:
    create: true

service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
    cluster: 7077
  externalTrafficPolicy: Cluster
  sessionAffinity: None

ingress:
  enabled: true
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: spark.local
  ingressClassName: ""
  path: /
  annotations: {}
  tls: false
  selfSigned: false